// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDt4PVUlzp-KXNFw7iLxw3Johqx99Yp48Y',
    appId: '1:1064990210827:web:144725b0f2bc67432a000e',
    messagingSenderId: '1064990210827',
    projectId: 'projetointegrador-4fabf',
    authDomain: 'projetointegrador-4fabf.firebaseapp.com',
    databaseURL: 'https://projetointegrador-4fabf-default-rtdb.firebaseio.com',
    storageBucket: 'projetointegrador-4fabf.firebasestorage.app',
    measurementId: 'G-EBMWTYW189',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPn3GgeHFiyR3f_PXw5A7m3UiPbUhePHQ',
    appId: '1:1064990210827:android:089542472c37bfa52a000e',
    messagingSenderId: '1064990210827',
    projectId: 'projetointegrador-4fabf',
    databaseURL: 'https://projetointegrador-4fabf-default-rtdb.firebaseio.com',
    storageBucket: 'projetointegrador-4fabf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCy4bWdbAFxRrHXKpGP4YVSoMZ91A0wGtI',
    appId: '1:1064990210827:ios:06d573d95ec0ab432a000e',
    messagingSenderId: '1064990210827',
    projectId: 'projetointegrador-4fabf',
    databaseURL: 'https://projetointegrador-4fabf-default-rtdb.firebaseio.com',
    storageBucket: 'projetointegrador-4fabf.firebasestorage.app',
    iosClientId: '1064990210827-rt95q1tam0okjgvtbpbj62fp9fofhdm4.apps.googleusercontent.com',
    iosBundleId: 'com.example.projetoIntegrador',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCy4bWdbAFxRrHXKpGP4YVSoMZ91A0wGtI',
    appId: '1:1064990210827:ios:06d573d95ec0ab432a000e',
    messagingSenderId: '1064990210827',
    projectId: 'projetointegrador-4fabf',
    databaseURL: 'https://projetointegrador-4fabf-default-rtdb.firebaseio.com',
    storageBucket: 'projetointegrador-4fabf.firebasestorage.app',
    iosClientId: '1064990210827-rt95q1tam0okjgvtbpbj62fp9fofhdm4.apps.googleusercontent.com',
    iosBundleId: 'com.example.projetoIntegrador',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDt4PVUlzp-KXNFw7iLxw3Johqx99Yp48Y',
    appId: '1:1064990210827:web:906013b95be53c162a000e',
    messagingSenderId: '1064990210827',
    projectId: 'projetointegrador-4fabf',
    authDomain: 'projetointegrador-4fabf.firebaseapp.com',
    databaseURL: 'https://projetointegrador-4fabf-default-rtdb.firebaseio.com',
    storageBucket: 'projetointegrador-4fabf.firebasestorage.app',
    measurementId: 'G-ME2FQP2T3K',
  );

}