// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkrzQA5TEMNyJeg15FVSxk3rTGthuZkpA',
    appId: '1:300037370787:web:2770aae3c81908a06a6016',
    messagingSenderId: '300037370787',
    projectId: 'icev-97775',
    authDomain: 'icev-97775.firebaseapp.com',
    databaseURL: 'https://icev-97775-default-rtdb.firebaseio.com',
    storageBucket: 'icev-97775.firebasestorage.app',
    measurementId: 'G-1LGKJDXN2T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCg8M9CdOQdy2AbFCvJnBiMkvkiTc_jjlk',
    appId: '1:300037370787:android:123691171fcec8546a6016',
    messagingSenderId: '300037370787',
    projectId: 'icev-97775',
    databaseURL: 'https://icev-97775-default-rtdb.firebaseio.com',
    storageBucket: 'icev-97775.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFIgP1Q96E6QaReOQjenz_WcCxEsfdLg8',
    appId: '1:300037370787:ios:7dddc990d5da56cb6a6016',
    messagingSenderId: '300037370787',
    projectId: 'icev-97775',
    databaseURL: 'https://icev-97775-default-rtdb.firebaseio.com',
    storageBucket: 'icev-97775.firebasestorage.app',
    iosBundleId: 'com.example.projetoIntegrador',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFIgP1Q96E6QaReOQjenz_WcCxEsfdLg8',
    appId: '1:300037370787:ios:7dddc990d5da56cb6a6016',
    messagingSenderId: '300037370787',
    projectId: 'icev-97775',
    databaseURL: 'https://icev-97775-default-rtdb.firebaseio.com',
    storageBucket: 'icev-97775.firebasestorage.app',
    iosBundleId: 'com.example.projetoIntegrador',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkrzQA5TEMNyJeg15FVSxk3rTGthuZkpA',
    appId: '1:300037370787:web:238b0c54faef3b756a6016',
    messagingSenderId: '300037370787',
    projectId: 'icev-97775',
    authDomain: 'icev-97775.firebaseapp.com',
    databaseURL: 'https://icev-97775-default-rtdb.firebaseio.com',
    storageBucket: 'icev-97775.firebasestorage.app',
    measurementId: 'G-MYRTZ49HJ3',
  );
}
